### ISSUE TITLE
Dúvida: não seria mais correto utilizar a acurácia de etapa de teste para comparar diversity com força bruta?

### ISSUE THREAD

**Issue by fernandaborgesdasilva** [fernandaborgesdasilva/evolutionary_ensemble#13]
Minha dúvida está relacionada ao fato de estarmos avaliando somente qual dos dois tem melhor performance no dataset de treinamento, desconsiderando a questão da generalização.

Fiquei pensando nisso principalmente porque no diversity utilizamos um critério de diversidade que pode ser identificado como uma "vantagem" somente quando a questão da variância é levada em consideração.

**Comment by covoes** [comment]
Mas estamos no processo de "treinamento" do ensemble, encontrar o melhor conjunto. Não podemos usar a base de teste final para escolher esse conjunto.
No entanto, a diversidade considera o erro de validação cruzada, ou seja, o erro quando o objeto não está sendo usado no treinamento do classificador.
